const fs = require('fs');
const text = fs.readFileSync('src/app/dashboard/page.tsx', 'utf8');
const lines = text.split(/\r?\n/);
const start = 493 - 1;
const end = 1151 - 1;
const region = lines.slice(start, end + 1).join('\n');
const openDiv = (region.match(/<div(\s|>|\/)/g) || []).length;
const closeDiv = (region.match(/<\/div>/g) || []).length;
const openMain = (region.match(/<main(\s|>|\/)/g) || []).length;
const closeMain = (region.match(/<\/main>/g) || []).length;
console.log('openDiv', openDiv, 'closeDiv', closeDiv, 'openMain', openMain, 'closeMain', closeMain);
